name: "Verify type labels"

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: "bug, fix, feature, maintenance"
